### ISSUE TITLE
change from yesterday broke bower install

### ISSUE THREAD

**Issue by peterberkman** [isaacs/chownr#18]
[INFO] --- frontend-maven-plugin:1.0:bower (bower install) @ framework-fe ---
[INFO] Running 'bower install' in D:\Source\nextgate\Products\common\trunk\ui\framework-fe\target\uibuild
[ERROR] bower                            error Use of const in strict mode.
[ERROR]
[ERROR] D:\Source\nextgate\Products\common\trunk\ui\framework-fe\target\uibuild\node_modules\bower\node_modules\tar-fs\node_modules\chownr\chownr.js:2
[ERROR] const fs = require('fs')
[ERROR] ^^^^^

**Comment by isaacs** [comment]
This is a strange error.  What version of node are you using?  When support for const was added in v4, it _required_ strict mode.

**Comment by LeoK80** [comment]
hi, we've got the same issue as it's a transitive dependency for the package `tar-fs` used by some older bower version (specified as `"chownr": "^1.0.1"` in its dependencies) https://github.com/mafintosh/tar-fs/blob/master/package.json. (package `tar` within `fsevents` dependencies also refer to this package in the same manner).
As you've changed the syntax from oldschool JS to ES6 it probably should be a v2.0.0 (breaking change) instead of 1.1.x in which case consumers of old version libraries won't have their bower builds break 👍

**Comment by peterberkman** [comment]
> This is a strange error. What version of node are you using? When support for const was added in v4, it _required_ strict mode.

it is old...   we corrected it by upgrading to the latest.  However, we have hundreds of past branches that will now have this problem.  probably should have been a major rev as apposed to a patch rev....

**Comment by Me1000** [comment]
This problem is going to be pervasive as many people are running older versions of node (for valid reasons).

This is a breaking change and should have been published as 2.0.0.

**Comment by lpd-au** [comment]
@isaacs I believe this will break in versions like 0.10 and 0.12

**Comment by betoborda** [comment]
I got exactly the same problem. 

> hi, we've got the same issue as it's a transitive dependency for the package `tar-fs` used by some older bower version (specified as `"chownr": "^1.0.1"` in its dependencies) https://github.com/mafintosh/tar-fs/blob/master/package.json. (package `tar` within `fsevents` dependencies also refer to this package in the same manner).
> As you've changed the syntax from oldschool JS to ES6 it probably should be a v2.0.0 (breaking change) instead of 1.1.x in which case consumers of old version libraries won't have their bower builds break 👍

**Comment by isaacs** [comment]
At this point, I'm sorry, but if you're using insecure node versions that are long out of LTS, then that takes a bit of extra work.

In your top-level project's package.json file, add `"chownr": "1.0.1"` to your dependencies stanza.

**Comment by Me1000** [comment]
Can I just ask the reasoning behind not just keeping the 1.x.x line compatible, and publishing this set of changes under the 2.x.x line? Certainly no one is arguing against these changes, I think we all agree they are good improvments, but I think its worthwhile to empathize with the fact that this is a **patch level change** (0.0.1) being published **3 full years** after the last update (so its not like this is a library that changes often and people are used to monitoring), so will almost certainly be a very big surprise for a lot of people. This is especially true when you consider that an accompanying `engines` change with `node: ">= 4.x.x"` was not included to at least provide some clue as to why a hard-to-understand error was taking place, quite possibly deep in your subdependency tree.

Regarding coupling the responsibility of providing a strict semver version (vs the ~1.0.0 range automatically generated by npm installs) with "using a secure version of node", I think this is troublesome for a number of reasons. For starters, nothing in this failure indicates that the real problem is that you are using the wrong version of node (as mentioned above which would at least be remedied with `engines`). Separately, and perhaps more importantly, I think this hurts people's general understanding, and confidence, of the node and semver ecosystems. The contract semver forms is that these sorts of patch level changes should not be breaking, and it is very confusing when that is not the case, and perpetuates the "software is magic and too hard fo rme" feeling a lot of people get.

**Comment by lpd-au** [comment]
Me1000, I agree. @isaacs, you should republish v1.1.x as v2.0.x and include a nodejs version requirement of >= 10.6 in package.json. Afterwards, publish a v1.1.2 that undoes the breaking changes but marks the major version as deprecated and vulnerable.
