### ISSUE TITLE
Symlinks problem

### ISSUE THREAD

**Issue by missingdays** [isaacs/chownr#3]
The same issue we had with chmodr.
Script walks on symlinks and tries to change permissions on every file there.
chmdod -R doesn't do that.
#2 closes this.

**Comment by simevo** [comment]
AFAICT this is now addressed on master since somehow the PR #2 has been actually merged. So this bug _could_ be closed.
But the fix introduced #14.
An alternative fix would have been to use [lchown](https://nodejs.org/api/fs.html#fs_fs_lchown_path_uid_gid_callback) rather than chown. lchown does not dereference symbolic links and merely changes the owner of the link.
Would that be acceptable ?

**Comment by isaacs** [comment]
Fixed in v1.1.0.  The fix for chmodr is a bit more complicated, because `lchmod` is implemented in a way that cannot work on directories.
